openapi: "3.0.3"
info:
  title: Schemas for Activities page.
  version: ${project.version}
paths:
  /schemas/activities:
    summary: Contains only schema objects.

components:
  schemas:
    ActivityPage:
      allOf:
        - $ref: "./pageBase.yaml#/components/schemas/PageBase"
        - type: object
          required:
            - content
          properties:
            content:
              type: array
              items:
                $ref: "#/components/schemas/Activity"
    Activity:
      type: object
      required:
        - id
        - name
        - group
        - overdue
        - schedules
        - lastCompleted
        - daysSinceCompletion
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        group:
          $ref: "./groups.yaml#/components/schemas/SimpleGroupRepresentation"
        overdue:
          type: boolean
        schedules:
          $ref: "./schedules.yaml#/components/schemas/Schedules"
        lastCompleted:
          type: string
          format: date-time
        daysSinceCompletion:
          type: integer
          format: int32

    CreateActivityRequest:
      type: object
      required:
        - name
        - groupId
      properties:
        name:
          type: string
        groupId:
          type: integer
          format: int64

    PatchActivityRequest:
      type: object
      properties:
        name:
          type: string
        groupId:
          type: integer
          format: int64


    ActivityDeletionImpact:
      type: object
      required:
        - name
        - associatedTasks
        - associatedUncompletedTasks
      properties:
        name:
          type: string
        associatedTasks:
          type: integer
        associatedUncompletedTasks:
          type: integer


    SimpleActivityRepresentation:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "Replace my toothbrush"
