openapi: "3.0.3"
info:
  title: Schemas for Groups page.
  version: ${project.version}
paths:
  /schemas/groups:
    summary: Contains only schema objects.

components:
  schemas:
    GroupPage:
      allOf:
        - $ref: "./pageBase.yaml#/components/schemas/PageBase"
        - type: object
          required:
            - content
          properties:
            content:
              type: array
              items:
                $ref: "#/components/schemas/Group"
    Group:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        activities:
          type: array
          items:
            $ref: "#/components/schemas/ActivitySummary"

    ActivitySummary:
      type: object
      required:
        - id
        - name
        - overdue
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        overdue:
          type: boolean

    CreateGroupRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Personal care"

    SimpleGroupRepresentation:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "Personal care"

    GroupDeletionImpact:
      type: object
      required:
        - name
        - associatedActivities
        - associatedTasks
        - associatedUncompletedTasks
      properties:
        name:
          type: string
        associatedActivities:
          type: integer
        associatedTasks:
          type: integer
        associatedUncompletedTasks:
          type: integer







