openapi: "3.0.3"
info:
  title: Schemas for Tasks page.
  version: ${project.version}
paths:
  /schemas/tasks:
    summary: Contains only schema objects.

components:
  schemas:
    TaskPage:
      allOf:
        - $ref: "./pageBase.yaml#/components/schemas/PageBase"
        - type: object
          required:
            - content
          properties:
            content:
              type: array
              items:
                $ref: "#/components/schemas/Task"
    Task:
      type: object
      required:
        - id
        - activity
        - group
        - dueDate
        - status
        - daysOverdue
        - completionDate
        - daysSinceCompletion
      properties:
        id:
          type: integer
          format: int32
        activity:
          $ref: "./activities.yaml#/components/schemas/SimpleActivityRepresentation"
        group:
          $ref: "./groups.yaml#/components/schemas/SimpleGroupRepresentation"
        dueDate:
          type: string
          format: date-time
        status:
          $ref: "#/components/schemas/TaskStatus"
        daysOverdue:
          type: integer
          format: int32
        completionDate:
          type: string
          format: date-time
        daysSinceCompletion:
          type: integer
          format: int32
          minimum: 1

    CreateTaskRequest:
      type: object
      required:
        - activityId
      properties:
        activityId:
          type: integer
          format: int32
        dueDate:
          type: string
          format: date-time
        completionDate:
          type: string
          format: date-time

    PatchTaskRequest:
      type: object
      properties:
        activityId:
          type: integer
          format: int32
        dueDate:
          type: string
          format: date-time
        completionDate:
          type: string
          format: date-time


    ActivityDeletionImpact:
      type: object
      required:
        - name
        - associatedTasks
        - associatedUncompletedTasks
      properties:
        name:
          type: string
        associatedTasks:
          type: integer
        associatedUncompletedTasks:
          type: integer


    TaskStatus:
      type: integer
      format: int32
      enum: [ 0, 1, 2 ]
      description: |
        Task status:
        - 0: TODO
        - 1: OVERDUE
        - 2: COMPLETED
